version: '3.9'

services:
  controller:
    build:
      context: .
      dockerfile: AppsTester.Controller/Dockerfile
    environment:
      ConnectionStrings__RabbitMq: amqp://root:root@rabbitmq:5672
  android-checker:
    build:
      context: .
      dockerfile: AppsTester.Checker.Android/Dockerfile
    environment:
      ConnectionStrings__RabbitMq: amqp://root:root@rabbitmq:5672
  rabbitmq:
    image: rabbitmq:3.8.26-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'root'
      RABBITMQ_DEFAULT_PASS: 'root'
    volumes:
      - ./dev-data/rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
